### PR TITLE
Fix loading of statements. Closes #1788

### LINKED ISSUE #1788: NoMethodError: undefined method `publication_title' for nil:NilClass
Sentry Issue: [PUBLISHERS-PRODUCTION-T2-8GC](https://sentry.io/organizations/brave-software/issues/918972239/?project=225116&referrer=github_integration)

```
NoMethodError: undefined method `publication_title' for nil:NilClass
  app/services/publisher_statement_getter.rb:45:in `block in replace_account_identifiers_with_titles'
    transaction["channel"] = channel.publication_title
  app/services/publisher_statement_getter.rb:39:in `map'
    transactions.map { |transaction|
  app/services/publisher_statement_getter.rb:39:in `replace_account_identifiers_with_titles'
    transactions.map { |transaction|
  app/services/publisher_statement_getter.rb:12:in `perform'
    transactions = replace_account_identifiers_with_titles(transactions)
  lib/error_handler_delegator.rb:13:in `block in method_missing'
    @target.send(*args, &block)
...
(109 additional frame(s) were not displayed)

NoMethodError: undefined method `publication_title' for nil:NilClass
```

### PR DESCRIPTION
**Pull request by yachtcaptain23**
## Pull Request Name

[Add screenshot if applicable]

#### Features

Enter a brief summary of the Pull Request - Features, motivations, and issues it #closes

#### How To Test

1. Step one
2. Step two
3. Step three

#### Pull Request Checklist

- [ ] Adequate test coverage exists to prevent regressions -- [Guide to Testing](https://guides.rubyonrails.org/testing.html)
- [ ] XSS is mitigated -- [Guide to XSS Prevention](https://guides.rubyonrails.org/security.html#cross-site-scripting-xss)
- [ ] No raw SQL -- [Guide to SQL Injection Prevention](https://guides.rubyonrails.org/security.html#sql-injection)
- [ ] UI/UX is responsive -- [Guide to Responsive UI/UX](https://developers.google.com/web/fundamentals/design-and-ux/responsive/)
- [ ] Integrated Matomo for new UI elements -- [Guide to Matomo](https://developer.matomo.org/guides/integrate-introduction)
- [ ] Passes checklist for Progressive Web App -- [Guide to PWAs](https://developers.google.com/web/progressive-web-apps/checklist)

### CODE REVIEW

File: app/services/publisher_statement_getter.rb [hunk 1]
```diff
@@ -40,6 +40,8 @@ def replace_account_identifiers_with_titles(transactions)
       account_identifier = transaction["channel"]
       if account_identifier.starts_with?(Publisher::OWNER_PREFIX)
         transaction["channel"] = "All"
+      elsif account_identifier.blank?
+        transaction["channel"] = "Manual"
```
Comment (dlipeles) [inline app/services/publisher_statement_getter.rb]: Consider 

```ruby
  transaction["channel"] = PotentialPayment::MANUAL
```

Comment (yachtcaptain23) [reply app/services/publisher_statement_getter.rb]: "Manual" is a label from the transactions table.
