### PR TITLE
Choose the right piwik host to prevent blocking

### LINKED ISSUE #2165: Bug: Piwik reporting not working for reporting users using publishers.basicattentiontoken.org
Brave Browser blocks cross-origin hosted piwik.js. We're underreporting views and other metrics.

### PR DESCRIPTION
**Pull request by yachtcaptain23**
Closes #2165

## Pull Request Name

[Add screenshot if applicable]

#### Features

Enter a brief summary of the Pull Request - Features, motivations, and issues it #closes

#### How To Test

1. Step one
2. Step two
3. Step three

#### Pull Request Checklist

- [ ] Adequate test coverage exists to prevent regressions -- [Guide to Testing](https://guides.rubyonrails.org/testing.html)
- [ ] XSS is mitigated -- [Guide to XSS Prevention](https://guides.rubyonrails.org/security.html#cross-site-scripting-xss)
- [ ] No raw SQL -- [Guide to SQL Injection Prevention](https://guides.rubyonrails.org/security.html#sql-injection)
- [ ] UI/UX is responsive -- [Guide to Responsive UI/UX](https://developers.google.com/web/fundamentals/design-and-ux/responsive/)
- [ ] Integrated Matomo for new UI elements -- [Guide to Matomo](https://developer.matomo.org/guides/integrate-introduction)
- [ ] Passes checklist for Progressive Web App -- [Guide to PWAs](https://developers.google.com/web/progressive-web-apps/checklist)

### CODE REVIEW

File: app/helpers/application_helper.rb [hunk 1]
```diff
@@ -2,4 +2,15 @@ module ApplicationHelper
   def popover_menu(&block)
     render(layout: "popover", &block)
   end
+
+  def piwik_domain
+    piwik_domain = ""
+    begin
+      host = URI.parse(request.original_url).host
+      domain = "#{PublicSuffix.parse(host).domain}"
+      piwik_domain = "#{Rails.application.secrets[:piwik_host_prefix]}.#{domain}" if domain.in?(["basicattentiontoken.org", "brave.com"])
```
Comment (corymcdonald) [inline app/helpers/application_helper.rb]: I don't see any corresponding changes to the secrets file, should we update?

File: config/secrets.yml [hunk 2]
```diff
@@ -35,6 +35,7 @@ default: &default
   # Piwik analytics endpoint with trailing slash e.g. https://piwik.example.com/
   piwik_host: <%= ENV["PIWIK_HOST"] %>
```
Comment (corymcdonald) [inline config/secrets.yml]: Can we remove this unused secret?
