### PR TITLE
Destroy Uphold Wallets Instead of Clearing

### LINKED ISSUE #3271: TwoFactorAuthenticationRemoval failing due to selected_wallet_provider being nil
There's a bug where if no selected wallet exists, we hit a nil exception here https://github.com/brave-intl/publishers/blob/staging/app/models/uphold_connection.rb#L98

We should just destroy the connections like we do for gemini and bitflyer.

### PR DESCRIPTION
**Pull request by tsmartt**
We need to keep track of deletions of wallet connections, so
we add papertrail on gemini and bitflyer.

We also now just destroy the uphold connection when disconnecting,
this will fix the issue with TwoFactorAuth removal as well as
bring it into line with the other connection types.

### CODE REVIEW

File: test/controllers/publishers_controller_test.rb [hunk 1]
```diff
@@ -519,7 +515,7 @@ def request_login_email_uppercase_email(publisher:)
     assert_response 200
 
     publisher.reload
-    refute publisher.uphold_connection.uphold_verified?
+    refute publisher.uphold_connection
```
Comment (tsmartt) [inline test/controllers/publishers_controller_test.rb:518]: This is the real test change. The rest was Rubocop formatting the file, which was apparently not in good shape.

**Review by yachtcaptain23 — APPROVED** [review]
LG2M. Please change PR header
