### PR TITLE
Fix channel transfer bug. Closes #2400

### LINKED ISSUE #2400: NoMethodError: undefined method `empty?' for nil:NilClass
Sentry Issue: [PUBLISHERS-PRODUCTION-T2-9RT](https://sentry.io/organizations/brave-software/issues/1281589113/?referrer=github_integration)

```
NoMethodError: undefined method `empty?' for nil:NilClass
  app/controllers/channel_transfer_controller.rb:17:in `verify_token'
    if @current_channel.nil? || @current_channel.contest_token.empty? || @current_channel.contest_token != params[:token_id]
  app/controllers/application_controller.rb:37:in `switch_locale'
    I18n.with_locale(locale, &action)
  config/middlewares/http_header_middleware.rb:8:in `call'
    @app.call(env)
...
(124 additional frame(s) were not displayed)

NoMethodError: undefined method `empty?' for nil:NilClass
```

### PR DESCRIPTION
**Pull request by yachtcaptain23**

### CODE REVIEW

File: app/controllers/channel_transfer_controller.rb [hunk 1]
```diff
@@ -14,7 +14,7 @@ def reject_transfer
 
   def verify_token
     @current_channel = Channel.find(params[:id])
-    if @current_channel.nil? || @current_channel.contest_token.empty? || @current_channel.contest_token != params[:token_id]
+    if @current_channel.nil? || @current_channel.contest_token.nil? || @current_channel.contest_token != params[:token_id]
```
Comment (corymcdonald) [inline app/controllers/channel_transfer_controller.rb]: Let's use the `.blank?` method instead as it covers the most cases for when an object is `nil`, `""`, `" "` or some other edge case.
```suggestion
    if @current_channel.nil? || @current_channel.contest_token.blank? || @current_channel.contest_token != params[:token_id]
```
Here's a handy chart for the difference s between, `nil?`, `empty?`, and `blank?`
