### PR TITLE
Devise shows t.devise.failure.timeout after a user signs in. Removing…

### LINKED ISSUE #2082: Fix erroneous flash banners for users who just signed in
After we had resolved the expired login bug, we have erroneous flash messages at the top. It's a bit annoying to see these messages that are wrong, so we should fix or just remove them entirely.

### PR DESCRIPTION
**Pull request by yachtcaptain23**
… this line removes the message by not forcing a sign out. Closes #2082 

## Pull Request Name

[Add screenshot if applicable]

#### Features

Enter a brief summary of the Pull Request - Features, motivations, and issues it #closes

#### How To Test

1. Step one
2. Step two
3. Step three

#### Pull Request Checklist

- [ ] Adequate test coverage exists to prevent regressions -- [Guide to Testing](https://guides.rubyonrails.org/testing.html)
- [ ] XSS is mitigated -- [Guide to XSS Prevention](https://guides.rubyonrails.org/security.html#cross-site-scripting-xss)
- [ ] No raw SQL -- [Guide to SQL Injection Prevention](https://guides.rubyonrails.org/security.html#sql-injection)
- [ ] UI/UX is responsive -- [Guide to Responsive UI/UX](https://developers.google.com/web/fundamentals/design-and-ux/responsive/)
- [ ] Integrated Matomo for new UI elements -- [Guide to Matomo](https://developer.matomo.org/guides/integrate-introduction)
- [ ] Passes checklist for Progressive Web App -- [Guide to PWAs](https://developers.google.com/web/progressive-web-apps/checklist)

### CODE REVIEW

File: app/controllers/publishers_controller.rb [hunk 1]
```diff
@@ -266,8 +266,6 @@ def get_site_banner_data
   private
 
   def authenticate_via_token
-    sign_out(current_publisher) if current_publisher
```
Comment (corymcdonald) [inline app/controllers/publishers_controller.rb]: Could this raise an exception if we continue down with the method with an already signed in user? 

Perhaps we should just return if they are already authenticated? (Not sure about that one)

Comment (yachtcaptain23) [reply app/controllers/publishers_controller.rb]: I tested by: 
(0) Open mailcatcher in non-private window
(1) Signing in a non-private window for a@a.com
(2) Fetching a login email in a private window for b@b.com
(3) In non-private window, clicking on the link in mailcatcher for b@b.com
(4) See that session has switched to b@b.com
