### PR TITLE
Fix Localization in React

### LINKED ISSUE #2345: Fix Localization in React
Sentry Issue: [PUBLISHERS-PRODUCTION-T2-9TE](https://sentry.io/organizations/brave-software/issues/1296332258/?referrer=github_integration)

```
ArgumentError: invalid date
  app/controllers/publishers/promo_registrations_controller.rb:17:in `overview'
    start_date = (params[:month]&.to_date || Date.today).at_beginning_of_month
  app/controllers/application_controller.rb:37:in `switch_locale'
    I18n.with_locale(locale, &action)
  config/middlewares/http_header_middleware.rb:8:in `call'
    @app.call(env)
...
(123 additional frame(s) were not displayed)

ArgumentError: invalid date
```

### PR DESCRIPTION
**Pull request by corymcdonald**
## Fixes Localization in React

Screen Shot 2019-10-28 at 4 35 13 PM
Screen Shot 2019-10-28 at 4 35 06 PM
Screen Shot 2019-10-28 at 4 35 03 PM

#### Features

Closes #2345

### How to test

Load up the home page and pass `locale=ja` and the homepage loads correctly

### CODE REVIEW

File: app/javascript/locale/ja.ts [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+      installed: "インストール済み",
+      statement: "この期間の支払いについては、明細を確認してください。",
+      title: "紹介プロモーションの統計"
+    }
+  },
+  settings: {
+    contact: {
+      edit: "編集",
+      email: '新しいメール',
+      error: "Unable to change email; the email address may be in use. Please enter a different email address.",
```
Comment (corymcdonald) [inline app/javascript/locale/ja.ts]: We're missing some translations here, but i'm not sure what the proper process would be for this
