### PR TITLE
Fix an issue where site channel that's not verified gets transferred …

### LINKED ISSUE #2121: ActionView::Template::Error: undefined method `upcase_first' for nil:NilClass
Sentry Issue: [PUBLISHERS-PRODUCTION-T2-9FP](https://sentry.io/organizations/brave-software/issues/1144545543/?referrer=github_integration)

```
NoMethodError: undefined method `upcase_first' for nil:NilClass
  app/views/publishers/_channel.html.slim:54:in `_app_views_publishers__channel_html_slim__2202364751237971131_47099204843400'
    = channel_verification_details(channel).upcase_first
  app/views/publishers/home.html.slim:194:in `block in _app_views_publishers_home_html_slim___1439648303859512165_47099210048160'
    = render partial: 'channel', locals: { channel: channel }
  app/views/publishers/home.html.slim:193:in `_app_views_publishers_home_html_slim___1439648303859512165_47099210048160'
    - @publisher.channels.visible.each do |channel|
  config/middlewares/http_header_middleware.rb:8:in `call'
    @app.call(env)
...
(171 additional frame(s) were not displayed)

ActionView::Template::Error: undefined method `upcase_first' for nil:NilClass

ActionView::Template::Error: undefined method `upcase_first' for nil:NilClass
```

### PR DESCRIPTION
**Pull request by yachtcaptain23**
…and automatically gets marked as verified. Also fix multiple return types in ChannelsHelper. Closes #2121.

## Pull Request Name

[Add screenshot if applicable]

#### Features

Enter a brief summary of the Pull Request - Features, motivations, and issues it #closes

#### How To Test

1. Step one
2. Step two
3. Step three

#### Pull Request Checklist

- [ ] Adequate test coverage exists to prevent regressions -- [Guide to Testing](https://guides.rubyonrails.org/testing.html)
- [ ] XSS is mitigated -- [Guide to XSS Prevention](https://guides.rubyonrails.org/security.html#cross-site-scripting-xss)
- [ ] No raw SQL -- [Guide to SQL Injection Prevention](https://guides.rubyonrails.org/security.html#sql-injection)
- [ ] UI/UX is responsive -- [Guide to Responsive UI/UX](https://developers.google.com/web/fundamentals/design-and-ux/responsive/)
- [ ] Integrated Matomo for new UI elements -- [Guide to Matomo](https://developer.matomo.org/guides/integrate-introduction)
- [ ] Passes checklist for Progressive Web App -- [Guide to PWAs](https://developers.google.com/web/progressive-web-apps/checklist)

### CODE REVIEW

File: app/services/channels/approve_channel_transfer.rb [hunk 1]
```diff
@@ -17,8 +17,6 @@ def perform
         original_owner_name = @channel.publisher.name
         channel_name = @channel.publication_title
 
-        contested_by.verified = true
```
Comment (corymcdonald) [inline app/services/channels/approve_channel_transfer.rb]: I think we still need this, when a user transfers a channel it isn't marked as verified. We'd end up with scenarios where Youtube/Twitch/Twitter channels are transferred but not verified.
