### PR TITLE
Tell publishers why their site channel failed to verify

### LINKED ISSUE #711: Adding Site Channel: Missing way to correct "Channel could not be verified!"
Since #674/#655 if the user enters the token wrong they will see "Channel could not be verified!" with no way to "reenter" the channel to either choose a new method or check the instructions or token:

screen shot 2018-03-12 at 10 59 22 am

I propose we restore the previous behavior where clicking the channel will take the user to viewing the channel where they last left off (when they clicked verify).

From #655: "When an error has been encountered during domain verification, display that error for the channel and provide actionable steps. These scenarios will be spelled out further in a separate issue." I'm not sure how this is to be implemented, but it could provide an alternative way for the user to correct the problem instead of the above solution.

### PR DESCRIPTION
**Pull request by nvonpentz**
Resolves #711 

**This PR includes changes to the SiteChannelVerifier that should be reviewed and tested closely.**

How channels in various states appear on the dashboard:
image

Publishers can click "what happened" for unverified sites and see an explanation for why the verification failed.  This information is stored in the `verification_details` and is set by the SiteChannelVerifier:
image

After they click "verify" or "try again" from the dashboard, the modal will pop up with an explanation and a suggestion on how to fix:
image

When this PR is merged into production, an admin should replace all site channel details with verification_method `support_queue` to `nil`, as well as replace all channel details with verification_status `started` with `nil` or `failed`.

Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave-intl/publishers/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Tagged reviewers.
- [ ] Integrated piwik/matomo (for code that adds new buttons).
- [ ] Addressed or ignored all brakeman warnings

Test Plan:

Reviewer Checklist:

Tests
- [ ] Adequate test coverage exists to prevent regressions

Security:
- [ ] No raw SQL -- Always prefer ActiveRecord query helpers ([more info on StackOverflow](https://stackoverflow.com/questions/41410752/rails-5-sql-injection#41452695))
- [ ] XSS is mitigated -- Avoid `html_safe` and `raw`; escape untrusted content from users and 3rd party APIs ([Rails XSS guide](https://brakemanpro.com/2017/09/08/cross-site-scripting-in-rails) and [OWASP XSS Prevention Cheat Sheet](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet))

### CODE REVIEW

File: app/helpers/channels_helper.rb [hunk 1]
```diff
@@ -64,12 +64,65 @@ def channel_verification_status(channel)
...
+  def should_display_verification_token?(channel)
+    return false if channel.verified? || channel.details_type != "SiteChannelDetails"
+    ["no_txt_records", "token_incorrect_dns", "token_not_found_dns"].include?(channel.verification_details)
+  end
+
+  def capitalize_first_letter(str)
+    return if str.nil?
+    str[0] = str[0].capitalize
+    str
+  end
```
Comment (nvonpentz) [inline app/helpers/channels_helper.rb]: This method allows us to use the translations in `en.helpers.channels.verification_failure_explanation.*` either as a standalone sentence (dashboard) or a the second part of a sentence (verification failed modal) without having to duplicate the translations.

File: app/views/application/_icon_circled_x.html [hunk 2]
```diff
@@ -1,4 +1,4 @@
-<svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" viewBox="0 0 42 42">
+<svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" viewBox="0 0 42 42" class="icon-circled-x">
```
Comment (nvonpentz) [inline app/views/application/_icon_circled_x.html]: Adding a class here allows us to dynamically size the SVG with CSS

File: app/views/site_channels/verification_public_file.html.slim [hunk 3]
```diff
@@ -4,6 +4,9 @@
     publisher: current_publisher \
   }
 
+script type="text/html" id="verification_failed_modal_wrapper" data-open-verification-failed-modal="#{current_channel.verification_failed?}"
```
Comment (nvonpentz) [inline app/views/site_channels/verification_public_file.html.slim]: This script (here and on all of the verification pages) will load the modal if the channel's current `verification_status` has failed.  This has the unfortunate side effect of displaying the modal immediately after a publisher selects a new verification method.  I think ideally we show the failed verification modal only if the the failed attempt uses the method of the page the publisher is currently on.  I'll think about how to do this...

File: app/assets/stylesheets/pages/home.scss [hunk 4]
```diff
@@ -657,12 +660,62 @@
...
+        display: flex;
+        background: url(asset-path("icn-warning@1x.png")) no-repeat top left / 24px 24px;
         padding: 0 0 12px 38px;
         font-weight: bold;
         .btn {
-          margin: -8px 0 0 12px;
           vertical-align: top;
+          margin-left: 10px;
+        }
+        .verification-failed {
```
Comment (yachtcaptain23) [inline app/assets/stylesheets/pages/home.scss]: We may want to rename these to BEM style conventions.

File: app/helpers/channels_helper.rb [hunk 5]
```diff
@@ -64,12 +64,65 @@ def channel_verification_status(channel)
...
+        I18n.t("helpers.channels.verification_failure_cta.generic", support_email: Rails.application.secrets[:support_email])
+    end
+  end
+
+  def should_display_verification_token?(channel)
+    return false if channel.verified? || channel.details_type != "SiteChannelDetails"
+    ["no_txt_records", "token_incorrect_dns", "token_not_found_dns"].include?(channel.verification_details)
+  end
+
+  def capitalize_first_letter(str)
```
Comment (yachtcaptain23) [inline app/helpers/channels_helper.rb]: You can get rid of this method and just use `str.capitalize` according to https://stackoverflow.com/questions/3724913/capitalize-first-letter-in-ruby

File: config/locales/en.yml [hunk 6]
```diff
@@ -85,9 +85,33 @@ en:
       title: Frequently Asked Questions
   helpers:
     channels:
-      generic_verification_failure: Channel could not be verified!
       verification_in_progress: Verification in progress
-      verification_awaiting_admin_approval: Awaiting admin approval
+      verification_awaiting_admin_approval: Under review
+      verification_failure_what_happend: What happened
```
Comment (yachtcaptain23) [inline config/locales/en.yml]: Misspelling

File: app/helpers/channels_helper.rb (hunk 5 above)
Comment (nvonpentz) [reply app/helpers/channels_helper.rb]: sweet

Comment (nvonpentz) [reply app/helpers/channels_helper.rb]: @yachtcaptain23 Actually the reason why I didn't use this method is that it doesn't preserve the capitalization of the tail of the string.

```
irb(main):001:0> s = "we could not find the token in any of the TXT records."
irb(main):002:0> s.capitalize
=> "We could not find the token in any of the txt records."
```

I think we want to preserver the capitalization of "TXT".  Let me know if you'd like to keep the capitalize_first_letter method or create duplicate translations, or something else.

File: app/javascript/publishers/home.js [hunk 7]
```diff
@@ -347,6 +357,25 @@ document.addEventListener('DOMContentLoaded', function() {
...
+
+  // Hide all verification failed bubbles when anywhere on DOM is clicked
+  document.body.addEventListener('click', function(event) {
+    for (var i=0; i<verificationFailureWhatHappenedElements.length; i++) {
+      // Do not hide if the clicked element is supposed to show the bubble
+      let e = verificationFailureWhatHappenedElements[i];
+      if (e === event.target) {
+        continue;
+      } else {
+        hideVerificationFailureWhatHappenend(e);
```
Comment (yachtcaptain23) [inline app/javascript/publishers/home.js]: Should be `hideVerificationFailureWhatHappened`

Comment (nvonpentz) [reply app/javascript/publishers/home.js]: happened is a tough one for me apparently

File: app/models/channel.rb [hunk 8]
```diff
@@ -125,25 +119,30 @@ def verification_failed!(details = nil)
...
 
-  def verification_succeeded!(admin_approval)
-    if admin_approval
-      verification_status = 'approved_by_admin'
+  def verification_succeeded!(has_admin_approval)
+    if needs_admin_approval?
+      if has_admin_approval
+        verification_status = 'approved_by_admin'
+      else
+        raise VERIFICATION_RESTRICTION_ERROR
```
Comment (yachtcaptain23) [inline app/models/channel.rb]: I believe we want to append it to `errors` rather than raising an exception.

File: app/services/site_channel_verifier.rb [hunk 9]
```diff
@@ -3,32 +3,31 @@
...
-    return false if channel.verification_awaiting_admin_approval? && !admin_approval
+    return false if channel.verification_awaiting_admin_approval? && !has_admin_approval
 
-    @verified_channel_id = verify_publisher_id
-
-    if verified_channel_id.blank?
-      channel.verification_failed!
+    verification_result = verify_site_channel
+    
+    if verification_result == false
```
Comment (yachtcaptain23) [inline app/services/site_channel_verifier.rb]: `if verification_result.nil?` is more conventional

File: app/services/site_channel_verifier.rb [hunk 10]
```diff
@@ -3,32 +3,31 @@
...
-
-    update_verified_on_channel
-
-    unless channel.id == verified_channel_id
-      channel.verification_failed!
+    elsif channel.needs_admin_approval? && !has_admin_approval
+      channel.verification_awaiting_admin_approval!
       return false
+    else
+      channel.verification_succeeded!(has_admin_approval)
```
Comment (yachtcaptain23) [inline app/services/site_channel_verifier.rb]: You should check the errors resulting from `verification_succeeded!`

File: app/services/site_channel_verifier.rb [hunk 11]
```diff
@@ -37,125 +36,107 @@ def perform
...
-      else
-        verified_channel.verification_awaiting_admin_approval!
-        InternalMailer.channel_verification_approval_required(channel: verified_channel).deliver_later
-        SlackMessenger.new(message: "*Admin Action Required:* *#{verified_channel.publication_title}* on the restriction list verified by #{verified_channel.publisher.owner_identifier}; id=#{verified_channel.details.channel_identifier}").perform
-        return
-      end
-    end
-
-    verified_channel.verification_succeeded!(admin_approval)
+    verified_channel.verification_succeeded!(has_admin_approval)
```
Comment (yachtcaptain23) [inline app/services/site_channel_verifier.rb]: Same here I believe

File: app/views/publishers/home.html.slim [hunk 12]
```diff
@@ -210,32 +210,42 @@ script type="text/html" id="confirm_default_currency_modal_wrapper"
...
+              .channel-summary
+                h3= channel.publication_title
+                .channel-details
+                  .added-date
+                    = t ".channel.added", date: channel.created_at.to_date.iso8601
+            - elsif channel.verification_failed?
               .channel-status.float-right
-                = channel_verification_details(channel)
-                = link_to(t(".channel.try_again"), channel_next_step_path(channel), class: "btn btn-primary")
+                .verification-failed
```
Comment (yachtcaptain23) [inline app/views/publishers/home.html.slim]: IMO we should start breaking up the `home.html.slim` and merge as part of a `dashboard_partials` or `home_partials` folder just to make the folder not bloated.

File: app/services/site_channel_verifier.rb (hunk 9 above)
Comment (nvonpentz) [reply app/services/site_channel_verifier.rb]: `verify_site_channel` returns either returns `true` if the verification is successful, or `false` if not.  If it returns `false` it also sets `@verification_details` to the error, which is then later presented to the user.  So `verification_result.nil?` will always return `false` under this design.

We could have `verify_site_channel` return `nil` if the verification was successful and return the value of `@verification_details` if it wasn't.

File: config/locales/en.yml [hunk 13]
```diff
@@ -85,9 +85,31 @@ en:
...
+        domain_not_found: "we could not find your domain."
+        connection_failed: |
+          we could not find the public file at https://%{domain}/.well-known/brave-payments-verification.txt.
+        too_many_redirects: "we were redirected too many times to verify your domain. "
+        no_txt_records: "there are no TXT records on your domain's DNS. "
+        token_incorrect_dns: "the token in your TXT records is incorrect. "
+        token_not_found_dns: "we could not find the token in any of the TXT records. "
+        token_not_found_public_file: "we could not find the token in your public file. "
+        no_https: "HTTPS is not enabled. "
+        generic: "of an unkown reason. "
```
Comment (yachtcaptain23) [inline config/locales/en.yml]: Misspelling.

File: config/locales/en.yml [hunk 14]
```diff
@@ -85,9 +85,31 @@ en:
...
+      verification_failure_cta:
+        domain_not_found: "Please check if the domain is correct."
+        connection_failed: "Please make sure the file exists and is publicly available."
+        too_many_redirects: "Please reduce the number of redirects."
+        no_txt_records: "Please make sure you have entered the token in your DNS records:"
+        token_incorrect_dns: "Please make sure the token in your DNS entry is correct."
+        token_not_found_dns: "Please add this TXT entry to your DNS records:"
+        token_not_found_public_file_html: "Please make sure the verification token is present in the public file %{domain}/.well-known/brave-payments-verification.txt."
+        no_https: "Please enabled HTTPS on your domain, or choose another verification method."
+        generic: "Please contact %{support_email}."
```
Comment (yachtcaptain23) [inline config/locales/en.yml]: image

To be honest, the CTA is confusing since there's 2 conflicting CTAs (1. please email us and 2. Retry Verification). I think we should simplify this somehow, or even adjust the wording to say "If this verification failure continues to occur, please reach us at <email>".
