### PR TITLE
Case System improvements

### LINKED ISSUE #2068: When you close or accept a case it takes you to the next one
image

### LINKED ISSUE #2302: Add button to reject an already resolved Case
We should add a button to move a case back into reject once it's been accepted in case a user accidentally clicks the wrong button.

### LINKED ISSUE #2303: Next in queue for cases
Asad, Steven and Mattches would like the ability to go to the next case they have assigned automatically when they accept or reject a case.

image

### PR DESCRIPTION
**Pull request by corymcdonald**
## Case System improvements

Closes #2303
Closes #2302
Closes #2068

#### Features

* Rename some general translation strings
* Increase the pagination limit from 20 to 50
* Introduce ability to `OR` together search queries. Ex: Searching for `status:open status:in_progress` shows cases which are open or in progress
* Add ability to re-open case

### CODE REVIEW

File: app/controllers/admin/cases_controller.rb [hunk 1]
```diff
@@ -97,7 +87,43 @@ def update
...
+    private
+
+    def parse_search(search_case, queries)
+      statuses = queries.select { |x| x.include?("status") }.map { |x| x.split(':').last&.gsub(/[^0-9a-z_]/i, '') }
+      assigned = queries.select { |x| x.include?("assigned") }.map { |x| x.split(':').last&.gsub(/[^0-9a-z_]/i, '') }
+
+      first_status = statuses[0]
+      if first_status.present?
+        value = first_status
+        search_case = search_case.where('status LIKE ?', "%#{value}%")
```
Comment (yachtcaptain23) [inline app/controllers/admin/cases_controller.rb:109]: Instead of `status LIKE %value%`, would it be possible to use `where(status: value)` or `status LIKE value%`? Otherwise it'll be an O(n) search operation. 

From https://www.postgresql.org/docs/9.3/indexes-types.html
```
The optimizer can also use a B-tree index for queries involving the pattern matching operators LIKE and ~ if the pattern is a constant and is anchored to the beginning of the string — for example, col LIKE 'foo%' or col ~ '^foo', but not col LIKE '%bar'. 
```

Comment (corymcdonald) [reply app/controllers/admin/cases_controller.rb]: Yep! https://github.com/brave-intl/publishers/pull/2627/commits/0bb03e74fb8d1cbfbb6fb6ac5e649d264defde29

File: app/views/admin/shared/_sidebar.html.slim [hunk 2]
```diff
@@ -27,8 +27,6 @@ aside
           = nav_link "Approvals", admin_channel_approvals_path
           = nav_link "Duplicates", duplicates_admin_channels_path
 
-      = nav_link "Organizations", admin_organizations_path
```
Comment (yachtcaptain23) [inline app/views/admin/shared/_sidebar.html.slim:30]: Can we retain this? It's likely in near future we'll want to expand Organization for all publishers.

File: app/views/admin/cases/show.html.slim [hunk 3]
```diff
@@ -97,8 +97,10 @@
       - if @case.in_progress?
         .text-dark.justify-content-between.mb-2.align-items-center
           strong Actions
-        = link_to "Resolve", admin_case_path(@case, status: Case::RESOLVED), method: :patch, class: 'btn btn-success mx-1 mb-2'
-        = link_to "Close", admin_case_path(@case, status: Case::CLOSED), method: :patch, class: 'btn btn-dark mx-1 mb-2'
+        = link_to "Approve", admin_case_path(@case, status: Case::RESOLVED), method: :patch, class: 'btn btn-success mx-1 mb-2'
```
Comment (yachtcaptain23) [inline app/views/admin/cases/show.html.slim:100]: I originally named these `RESOLVED` and `CLOSED` to copy JIRA, in which the definitions are better defined here: https://community.atlassian.com/t5/Jira-questions/What-is-the-difference-between-closed-and-resolved-status-in/qaq-p/378505

I'm open to re-labeling, but I think @atsyed87 and his team should be aware.

File: app/controllers/admin/cases_controller.rb [hunk 4]
```diff
@@ -97,7 +87,43 @@ def update
...
+
+        statuses[1..-1].each do |value|
+          search_case = search_case.or(Case.where('status LIKE ?', "%#{value}%"))
+        end
+      end
+
+      first_assigned = assigned[0]
+      if first_assigned.present?
+        value = first_assigned
+        search_case = search_case.joins(:assignee).where('publishers.email LIKE ?', "%#{value}%")
```
Comment (yachtcaptain23) [inline app/controllers/admin/cases_controller.rb:119]: Would it be okay to use `publishers.email LIKE ?, "#{value}%` instead to make use of the index? Otherwise I'd prefer we'd read the read replica.

Same request applies to line 122

File: app/controllers/admin/cases_controller.rb [hunk 5]
```diff
@@ -97,7 +87,43 @@ def update
...
+    def parse_search(search_case, queries)
+      statuses = queries.select { |x| x.include?("status") }.map { |x| x.split(':').last&.gsub(/[^0-9a-z_]/i, '') }
+      assigned = queries.select { |x| x.include?("assigned") }.map { |x| x.split(':').last&.gsub(/[^0-9a-z_]/i, '') }
+
+      first_status = statuses[0]
+      if first_status.present?
+        value = first_status
+        search_case = search_case.where(status: value)
+
+        statuses[1..-1].each do |value|
```
Comment (yachtcaptain23) [inline app/controllers/admin/cases_controller.rb:111]: Block 111 to 114 can be refactored to 

```
search_case = search_case.where(status: statuses)
```

File: app/views/admin/shared/_sidebar.html.slim (hunk 2 above)
Comment (corymcdonald) [reply app/views/admin/shared/_sidebar.html.slim:30]: View code has already been deleted, I think we'd want a slight refactor, and expectations around how this would work 😄

File: app/views/admin/cases/show.html.slim (hunk 3 above)
Comment (corymcdonald) [reply app/views/admin/cases/show.html.slim:100]: This was a request from Asad to assist with training 👍

File: app/controllers/admin/cases_controller.rb (hunk 5 above)
Comment (corymcdonald) [reply app/controllers/admin/cases_controller.rb:111]: That would be an `AND` statement, rather than an `OR` which would result in no results. 😅

File: app/controllers/admin/cases_controller.rb (hunk 4 above)
Comment (corymcdonald) [reply app/controllers/admin/cases_controller.rb]: Sure thing! https://github.com/brave-intl/publishers/pull/2627/commits/4c5a3f976848852c38f029bd429474a475fb26e3

File: app/controllers/admin/cases_controller.rb (hunk 5 above)
Comment (yachtcaptain23) [reply app/controllers/admin/cases_controller.rb:111]: `statuses` is an array of `Case.status` right?

```
2.5.7 :006 > Case.where(status: ["closed", "open"]).to_sql
 => "SELECT \"cases\".* FROM \"cases\" WHERE \"cases\".\"status\" IN ('closed', 'open')"
Case.where(status: ["closed", "open"]).count
=> 548 // proves that it's not an AND
```

Comment (corymcdonald) [reply app/controllers/admin/cases_controller.rb]: Wow! that's awesome, had no idea.

https://github.com/brave-intl/publishers/pull/2627/commits/b4dec27a671494c732b67884ec1db5aa1767ef27
